apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-qa
spec:
  replicas: 3
  selector:
    app: nginx
    environment: qa
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        environment: qa
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-qa2
spec:
  replicas: 3
  selector:
    app: nginx
    environment: qa2
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        environment: qa2
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1
          ports:
            - containerPort: 80
